field: aec3f388-f651-4e63-aeff-ca02a1dc257d # Chapter Content Builder
fieldLayouts:
  65b31cc8-c282-49e4-b8ef-5839cebdf32b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: c1c6c30c-a910-4ee3-a2a3-c512d99b55b9 # Image Primary
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b4a9ee6f-fcb5-4ef6-8b12-0156815d8589
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b0e6bfc1-8a01-4693-9767-ecd14d449147 # Image Secondary
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d266c4db-78c4-4ff7-8cbc-cd8be93f7319
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 668547f1-151e-4a53-967e-8424f70c2163 # Body Text
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f3ec52d1-525d-4ac3-8d11-d448767e25de
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 26b9d54c-1a19-4ed5-b570-96385e46c574
        userCondition: null
fields:
  668547f1-151e-4a53-967e-8424f70c2163: # Body Text
    columnSuffix: vwdgenha
    contentColumnType: text
    fieldGroup: null
    handle: bodyText
    instructions: null
    name: 'Body Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      ckeConfig: 4b06473c-3b88-48b3-af83-ab4a681373bf # Link Only
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  b0e6bfc1-8a01-4693-9767-ecd14d449147: # Image Secondary
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imageSecondary
    instructions: null
    name: 'Image Secondary'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:214ab3d8-a393-45fc-a37a-bdead817a38f' # Hub Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:aeda56c8-0dfe-48c2-a8d4-e54a8d48906d' # Homepage
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:214ab3d8-a393-45fc-a37a-bdead817a38f' # Hub Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  c1c6c30c-a910-4ee3-a2a3-c512d99b55b9: # Image Primary
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: imagePrimary
    instructions: null
    name: 'Image Primary'
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:214ab3d8-a393-45fc-a37a-bdead817a38f' # Hub Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:aeda56c8-0dfe-48c2-a8d4-e54a8d48906d' # Homepage
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:214ab3d8-a393-45fc-a37a-bdead817a38f' # Hub Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: chapter1Block3
name: 'Chapter 1 Block 3'
sortOrder: 7
