field: aec3f388-f651-4e63-aeff-ca02a1dc257d # Chapter Content Builder
fieldLayouts:
  e2d41d11-34c0-495a-9f8a-7cc95112d41e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2f9d9023-21d8-4b66-9b35-ae7bbb7f053c # Display Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 28f4934c-56a4-4349-90e0-fdc8d63799cf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 54b01703-8cd9-43e2-815e-10950d4344e2 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99e38f3d-2d84-45a5-a275-70773458c5d4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4165b8b8-fa8e-43f1-9d72-c49f37a1af4c
        userCondition: null
fields:
  2f9d9023-21d8-4b66-9b35-ae7bbb7f053c: # Display Width
    columnSuffix: qycwrpxp
    contentColumnType: boolean
    fieldGroup: null
    handle: displayWidth
    instructions: null
    name: 'Display Width'
    searchable: false
    settings:
      default: false
      offLabel: 'Full Width'
      onLabel: Contained
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  54b01703-8cd9-43e2-815e-10950d4344e2: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      branchLimit: null
      defaultUploadLocationSource: 'volume:214ab3d8-a393-45fc-a37a-bdead817a38f' # Hub Assets
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: 1
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:aeda56c8-0dfe-48c2-a8d4-e54a8d48906d' # Homepage
      restrictedLocationSubpath: null
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources:
        - 'volume:214ab3d8-a393-45fc-a37a-bdead817a38f' # Hub Assets
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: fullWidthImage
name: 'Full Width Image'
sortOrder: 1
