field: 014f6ebf-7850-4cf6-ad76-967a93a7fd0a # Story Builder
fieldLayouts:
  3fcd75ce-e678-432f-b18b-d3490a563de6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: a146d795-daea-4647-928e-5d49262d76a9 # Anchor ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a5b0b46b-52f8-419b-90b6-b12507a77732
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 46355c78-58c6-4246-af17-67ccc52c511a # Container Width
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c4b110f7-0f78-4eea-883f-9fd705f08fce
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7aaeeed8-baa6-4eef-9613-3957ac520217 # Top Margin
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 757f44eb-d853-4fd3-b805-06503b4cb54a
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 83bc5521-552a-47c9-a738-80ef1c8d583a # Bottom Margin
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f044bb1-8185-49af-95fa-8bb46bac0621
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 65acfefd-5719-4d29-9550-57b90b1be761 # Rich Text Field
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 840ae5bb-fb3b-40c0-b1c5-4c734db83db4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 47a7608a-1352-46ee-9512-bfb3d8b77868
        userCondition: null
fields:
  7aaeeed8-baa6-4eef-9613-3957ac520217: # Top Margin
    columnSuffix: hymqybis
    contentColumnType: string
    fieldGroup: null
    handle: topMargin
    instructions: 'This is the spacing for the top of the block.'
    name: 'Top Margin'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - mt-0
            -
              - default
              - 1
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - mt-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - mt-regular
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - mt-large
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  65acfefd-5719-4d29-9550-57b90b1be761: # Rich Text Field
    columnSuffix: wgjelmyg
    contentColumnType: text
    fieldGroup: null
    handle: richTextField
    instructions: 'This is a rich text field that can bold, italicise, and create hyperlinks'
    name: 'Rich Text Field'
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      ckeConfig: d90da05d-83fd-4f3e-8812-240808f0689f # Story Builder RTF
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
      wordLimit: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  83bc5521-552a-47c9-a738-80ef1c8d583a: # Bottom Margin
    columnSuffix: koestyrx
    contentColumnType: string
    fieldGroup: null
    handle: bottomMargin
    instructions: 'This is the spacing for the bottom of the block.'
    name: 'Bottom Margin'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - mb-0
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - mb-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - mb-regular
            -
              - default
              - 1
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - mb-large
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  46355c78-58c6-4246-af17-67ccc52c511a: # Container Width
    columnSuffix: ocfcpukv
    contentColumnType: string
    fieldGroup: null
    handle: containerWidth
    instructions: 'This sets the maximum width that the RTF will be contained at.'
    name: 'Container Width'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - container
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Narrow'
            -
              - value
              - max-w-x-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - max-w-narrow
            -
              - default
              - 1
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - max-w-medium
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  a146d795-daea-4647-928e-5d49262d76a9: # Anchor ID
    columnSuffix: jwiwplwo
    contentColumnType: text
    fieldGroup: null
    handle: anchorId
    instructions: 'Add this to give the block a specific unique ID to target with CSS or anything else. This input should be in all lower-case with no spaces. Use hyphens instead of spaces.'
    name: 'Anchor ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: rtf
name: RTF
sortOrder: 3
