field: 2313d2e6-9c35-4082-9578-d4f0bf197786 # Stockist Locations
fieldLayouts:
  510db8f8-ff52-4008-a7e7-4d4dcda82806:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 683e8bc5-287f-43f5-bbde-cea43e376801 # City
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db37046d-00fd-4c96-8e05-21d7ffb69f3b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 557a4951-b322-4511-acbc-f658925c82c1 # Location Name
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2b72a97f-dd0b-4ef4-a762-4bd30850b03c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 784fcb90-385b-4fb7-8473-b907c20ee371 # Address
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3aff7b0-262b-49f7-804a-235351fcfc1f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d289ad29-f1b5-42bc-b002-32246df47eda # Telephone Number
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a9cd96c6-6d57-47ba-8d92-0fe91de85226
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 3e2af911-7ec8-47ad-8c7c-90d1c38a26f8 # Availability
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c553e6d2-b7a2-41e5-9155-9d036aa8e1a2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c5e112e4-4401-4bfc-bfe7-b72810ccb003 # Latitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ed20c3c6-d0cb-4b84-8286-42a77318f327
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: d6179036-bb08-4a4f-b0c9-62a5dd947147 # Longitude
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6a0f80a6-2d33-4048-be8f-fac3cfc9aec6
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 476e95d9-d016-4da0-9aef-58384be729d9
        userCondition: null
fields:
  3e2af911-7ec8-47ad-8c7c-90d1c38a26f8: # Availability
    columnSuffix: xqisqwml
    contentColumnType: string
    fieldGroup: null
    handle: availability
    instructions: null
    name: Availability
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Women
            -
              - value
              - women
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Men
            -
              - value
              - men
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\MultiSelect
  557a4951-b322-4511-acbc-f658925c82c1: # Location Name
    columnSuffix: lwfbjxyp
    contentColumnType: text
    fieldGroup: null
    handle: locationName
    instructions: null
    name: 'Location Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  683e8bc5-287f-43f5-bbde-cea43e376801: # City
    columnSuffix: kwdqmyxw
    contentColumnType: text
    fieldGroup: null
    handle: city
    instructions: null
    name: City
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  784fcb90-385b-4fb7-8473-b907c20ee371: # Address
    columnSuffix: oohsagmw
    contentColumnType: text
    fieldGroup: null
    handle: address
    instructions: null
    name: Address
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c5e112e4-4401-4bfc-bfe7-b72810ccb003: # Latitude
    columnSuffix: gtjsytov
    contentColumnType: text
    fieldGroup: null
    handle: latitude
    instructions: null
    name: Latitude
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d289ad29-f1b5-42bc-b002-32246df47eda: # Telephone Number
    columnSuffix: wvrfuguq
    contentColumnType: text
    fieldGroup: null
    handle: telNum
    instructions: null
    name: 'Telephone Number'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d6179036-bb08-4a4f-b0c9-62a5dd947147: # Longitude
    columnSuffix: jwizhora
    contentColumnType: text
    fieldGroup: null
    handle: longitude
    instructions: null
    name: Longitude
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: store
name: Store
sortOrder: 1
