field: 014f6ebf-7850-4cf6-ad76-967a93a7fd0a # Story Builder
fieldLayouts:
  a4e895e3-5425-4c6b-bce8-d5b3dac357b4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 1174568e-1964-4387-893b-29fa7af85cfc # Anchor ID
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d416a931-3e14-4a30-a756-61d0b6e1a6c9
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f39617f8-c534-446b-95a7-a3bbba253289 # Container Width
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10499861-897b-4a6b-824d-1a37bb710bb7
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 8cd34c54-e56e-4d0f-b7f3-714b08e692f2 # Top Margin
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2d257d1d-b6e0-41f2-9c2e-be3e8c3c3f46
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: eb6872b1-4282-487a-96d6-b8402acda74d # Bottom Margin
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a787f931-4ade-4e3e-a8ef-a2a6d3ce6c62
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 4044a603-09a5-4236-9ceb-ad91a8f7c371 # Video ID
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2f1f45f-0d81-4c35-b311-198b2027244b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: dc3985ce-0f72-4644-b8f5-d57a2118552c # Video Options
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b204dd05-aba6-403c-8b8b-582b189ecf45
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 2be6a176-d0d4-471f-bde4-b3ce87044d9a # Video Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f2219b7c-758b-4481-b5e2-be4927d3da1b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d6959dce-5733-4e86-b058-a64b8d002e64
        userCondition: null
fields:
  2be6a176-d0d4-471f-bde4-b3ce87044d9a: # Video Title
    columnSuffix: tlhmlwzt
    contentColumnType: text
    fieldGroup: null
    handle: videoTitle
    instructions: 'This is the title for the video.'
    name: 'Video Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8cd34c54-e56e-4d0f-b7f3-714b08e692f2: # Top Margin
    columnSuffix: cjirqnef
    contentColumnType: string
    fieldGroup: null
    handle: topMargin
    instructions: 'This is the spacing for the top of the block.'
    name: 'Top Margin'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - mt-0
            -
              - default
              - 1
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - mt-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - mt-regular
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - mt-large
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  4044a603-09a5-4236-9ceb-ad91a8f7c371: # Video ID
    columnSuffix: oqnbzcep
    contentColumnType: integer(10)
    fieldGroup: null
    handle: videoID
    instructions: 'This is the ID for the vimeo video'
    name: 'Video ID'
    searchable: false
    settings:
      decimals: 0
      defaultValue: null
      max: null
      min: 0
      prefix: null
      previewCurrency: null
      previewFormat: none
      size: null
      suffix: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Number
  1174568e-1964-4387-893b-29fa7af85cfc: # Anchor ID
    columnSuffix: sdjydtul
    contentColumnType: text
    fieldGroup: null
    handle: anchorId
    instructions: 'Add this to give the block a specific unique ID to target with CSS or anything else. This input should be in all lower-case with no spaces. Use hyphens instead of spaces.'
    name: 'Anchor ID'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  dc3985ce-0f72-4644-b8f5-d57a2118552c: # Video Options
    columnSuffix: auokpzac
    contentColumnType: string
    fieldGroup: null
    handle: videoOptions
    instructions: 'Options to enable on Vimeo videos.'
    name: 'Video Options'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Autoplay
            -
              - value
              - autoplay
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Controls
            -
              - value
              - controls
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Loop
            -
              - value
              - loop
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  eb6872b1-4282-487a-96d6-b8402acda74d: # Bottom Margin
    columnSuffix: qxlaxocf
    contentColumnType: string
    fieldGroup: null
    handle: bottomMargin
    instructions: 'This is the spacing for the bottom of the block.'
    name: 'Bottom Margin'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - None
            -
              - value
              - mb-0
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - mb-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - mb-regular
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Large
            -
              - value
              - mb-large
            -
              - default
              - 1
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  f39617f8-c534-446b-95a7-a3bbba253289: # Container Width
    columnSuffix: tkpsrpbv
    contentColumnType: string
    fieldGroup: null
    handle: containerWidth
    instructions: 'This sets the maximum width that the video will be contained at.'
    name: 'Container Width'
    searchable: false
    settings:
      columnType: string
      options:
        -
          __assoc__:
            -
              - label
              - Regular
            -
              - value
              - container
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Extra Narrow'
            -
              - value
              - max-w-x-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Narrow
            -
              - value
              - max-w-narrow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Medium
            -
              - value
              - max-w-medium
            -
              - default
              - 1
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: vimeo
name: Vimeo
sortOrder: 10
