fieldLayouts:
  1649c771-4a13-4d41-8f01-7cff764fb2dc:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9013a0d6-390c-483f-93c0-67e22252a810
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            heading: 'Primary Nav Type'
            type: craft\fieldlayoutelements\Heading
            uid: 9e265601-a1bf-47ab-861b-ae6e63750cc0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 86480226-b160-4ca3-9a81-2160cd00952c # Transparent Primary Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f826ef5f-a575-4454-9539-1aaa3394d502
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 86480226-b160-4ca3-9a81-2160cd00952c # Transparent Primary Nav
                  uid: 7361ba21-9811-41be-aaba-d8f4febff69a
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b78d2848-3680-4f07-8f04-4b69e65001d4 # Navigation Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 171a07bf-362e-461f-abcc-ff9c0ca1fde2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 28fab91a-b39e-47f6-9901-a10e7685d551
            userCondition: null
          -
            elementCondition: null
            fieldUid: dd5a83f5-ea0c-496f-a259-8994149740fc # Chapter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca3d03fc-b54e-4a91-83ed-0c0b67fda9d5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e409a0d6-eeee-4658-80de-7cf388590afe # Preview Card Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2a219f32-2dcb-45d5-89f3-bd827ecff45c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf4cbff0-5195-4ed6-866a-5d332970add1 # Hero Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b032313-01da-443d-ad50-9723f82e3551
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 3dcb0001-c4c6-4c7d-9511-e737959f7a92
            userCondition: null
          -
            elementCondition: null
            fieldUid: aec3f388-f651-4e63-aeff-ca02a1dc257d # Chapter Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 125ff328-37a6-4be2-8be7-5b27d0720d11
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b162fc22-c153-4d9d-af12-42b8155a51ed
        userCondition: null
handle: chapter3
hasTitleField: true
name: 'Chapter 3'
section: 5ba83fce-fdcb-4f60-b44c-850d08401c5a # Hub
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 4
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
