fieldLayouts:
  fb548bc6-ff04-435f-b93b-11851c05fc2c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 260d0c28-8bfa-45de-898d-fd7299e0c0e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Primary Nav Type'
            type: craft\fieldlayoutelements\Heading
            uid: f19ae8a4-cfb2-48b3-9178-161afa5d992a
            userCondition: null
          -
            elementCondition: null
            fieldUid: 86480226-b160-4ca3-9a81-2160cd00952c # Transparent Primary Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a810bfc0-71ff-4f29-ab1c-3da1189ae46b
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 86480226-b160-4ca3-9a81-2160cd00952c # Transparent Primary Nav
                  uid: b76f6e1e-2e75-43a1-a502-71d79a02fcd6
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b78d2848-3680-4f07-8f04-4b69e65001d4 # Navigation Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71a5c83c-40d8-4b8d-97ae-4127da66b6c7
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: ddb791e3-1b8c-4d42-8229-370d647375d6
            userCondition: null
          -
            elementCondition: null
            fieldUid: dd5a83f5-ea0c-496f-a259-8994149740fc # Chapter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a75407fb-1e19-4c71-af96-0eb84a8d9f86
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e409a0d6-eeee-4658-80de-7cf388590afe # Preview Card Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37de2472-bc31-4b2d-9e57-ebbba92e5f53
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: bf4cbff0-5195-4ed6-866a-5d332970add1 # Hero Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c290944e-5cc8-4022-84f4-ab5735e78ce2
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: d65eefb2-66cd-4dbc-a392-39c24849e626
            userCondition: null
          -
            elementCondition: null
            fieldUid: aec3f388-f651-4e63-aeff-ca02a1dc257d # Chapter Content Builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1915cbfb-a8a4-4f07-bf1b-37520c2fabaa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a3db3a06-8fd4-40ee-a3fe-cc3e793d9130
        userCondition: null
handle: chapter5
hasTitleField: true
name: 'Chapter 5'
section: 5ba83fce-fdcb-4f60-b44c-850d08401c5a # Hub
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 6
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
