fieldLayouts:
  bacdc730-8daf-490e-a49d-bc468abe6c6a:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: a87b27ae-7d19-4be3-aeb1-22eab3d589f5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Primary Navigation Type'
            type: craft\fieldlayoutelements\Heading
            uid: 753367c1-751b-420a-b84d-7cd4a5880f99
            userCondition: null
          -
            elementCondition: null
            fieldUid: 86480226-b160-4ca3-9a81-2160cd00952c # Transparent Primary Nav
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64a683cc-6b89-492b-8bf3-48272ee1843c
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: 86480226-b160-4ca3-9a81-2160cd00952c # Transparent Primary Nav
                  uid: 398d508f-e59e-488d-ac69-b2ea816d55ec
                  value: true
              elementType: craft\elements\Entry
              fieldContext: global
            fieldUid: b78d2848-3680-4f07-8f04-4b69e65001d4 # Navigation Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 67f2b00f-f601-465f-a960-fed618c4d06d
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: f727f44e-874e-4fd6-9f00-a9e6b8c0819c
            userCondition: null
          -
            elementCondition: null
            fieldUid: dd5a83f5-ea0c-496f-a259-8994149740fc # Chapter Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2af92496-6262-45a4-a8ae-a9e945194829
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: e409a0d6-eeee-4658-80de-7cf388590afe # Preview Card Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ca4a4e38-9f75-47db-a790-b3ab6d5f2711
            userCondition: null
            warning: null
            width: 50
        name: 'Chapter Content'
        uid: 4a2f3649-97c9-41dd-9535-b721f3bc361d
        userCondition: null
handle: default
hasTitleField: true
name: Default
section: 5ba83fce-fdcb-4f60-b44c-850d08401c5a # Hub
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
