defaultPlacement: end
fieldLayouts:
  5138be4c-54c5-47be-9d08-b84a9570dae2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 4a9e1ecb-b8f8-43ab-aefa-6de0bd409368
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            instructions: null
            label: null
            required: false
            tip: null
            type: verbb\navigation\fieldlayoutelements\NodeTypeElements
            uid: 3e2f242b-2333-4205-b286-8076a7994dd2
            userCondition: null
            warning: null
          -
            attribute: newWindow
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\NewWindowField
            uid: 93a6b670-4f41-4469-b3c1-dce8a351d6b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: df62c93f-2dc5-4f5a-9f1e-8b6093858b10 # isBlog
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e2e0c1d4-e087-43c1-82d5-f7f0beb9ac82
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1be69672-f2f1-4166-9db3-0a8db0efb654 # Primary Nav Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4a3caa0c-a5f2-4739-a711-63361f6a25dd
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1c71f697-1336-40e9-84fc-c1e2412e5cb5 # Image Info
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ea1df8d8-a213-4f97-a686-e066e3fadec1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: bf386f69-ee0d-4ad7-b0d7-d6f27b7e6e40 # Navigation Assets
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f53827d1-afd5-4d8e-b5d2-d1dc25148afa
            userCondition: null
            warning: null
            width: 100
        name: Node
        uid: b528cccc-44ec-464b-ac9f-5abbe67257ea
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            attribute: urlSuffix
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\UrlSuffixField
            uid: 8827f38e-e551-4d8d-a748-a535603236ae
            userCondition: null
            warning: null
            width: 100
          -
            attribute: classes
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            mandatory: false
            max: null
            maxlength: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            size: null
            step: null
            tip: null
            title: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\ClassesField
            uid: 90e68948-878a-4b97-8773-865c1a6f5087
            userCondition: null
            warning: null
            width: 100
          -
            attribute: customAttributes
            elementCondition: null
            id: null
            instructions: null
            label: null
            mandatory: false
            orientation: null
            requirable: true
            required: false
            tip: null
            translatable: false
            type: verbb\navigation\fieldlayoutelements\CustomAttributesField
            uid: 539afcee-a22d-49e5-8864-513a4630c6c1
            userCondition: null
            warning: null
            width: 100
        name: Advanced
        uid: bb3434ed-f299-41a0-aaed-e22797d4d74d
        userCondition: null
handle: primaryNavigation
instructions: ''
maxNodes: null
name: 'Primary Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  verbb\navigation\nodetypes\CustomType:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagationMethod: all
siteSettings:
  30a8fd08-2242-4239-8d98-6f56c65592a4: # Craft Portfolio
    enabled: true
sortOrder: 2
structure:
  maxLevels: null
  uid: 037e56ac-0952-4918-b84f-b6d25ac961dc
