baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Craft Portfolio'
primary: true
siteGroup: da133668-3cc3-4bbb-a785-743488b0c71d # Craft Portfolio
sortOrder: 1
