fieldLayouts:
  dd2ab110-c39b-4fb4-9125-ca62c66f0ac6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 59bb7581-cc54-4cdd-8f20-dd870ef62f3c
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 5757245b-d88e-44b2-bba0-bf1371909d8b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2fa369a7-5e91-4fc8-abd5-33af35c7a448
        userCondition: null
fs: timelineAssets
handle: timelineAssets
name: 'Timeline Assets'
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: timelineAssets
transformSubpath: ''
