columnSuffix: nzxrfxrx
contentColumnType: text
fieldGroup: 6091a114-c249-44fa-9a4a-66baa92bfd3b # Regional Sign-Up
handle: newsletterSuccessHeading
instructions: 'Heading for the newsletter success page.'
name: 'Newsletter Success Heading'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
