columnSuffix: dbxrqpao
contentColumnType: text
fieldGroup: a7520f9b-411b-4a62-9508-90b54dd1217c # Navigation
handle: phoneNumber
instructions: null
name: 'Phone Number'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
