columnSuffix: null
contentColumnType: string
fieldGroup: 1f0bf44d-ae4f-4e27-b3a0-78c91c9851fa # Common
handle: storyBuilder
instructions: null
name: 'Story Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_storybuilder}}'
  maxBlocks: null
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
