defaultPlacement: end
enableVersioning: true
handle: ourStory
name: 'Our Story'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  30a8fd08-2242-4239-8d98-6f56c65592a4: # Craft Portfolio
    enabledByDefault: true
    hasUrls: true
    template: our-story/_entry
    uriFormat: 'our-story/{slug}'
type: channel
