defaultPlacement: end
enableVersioning: true
handle: stockistLocator
name: 'Stockist Locator'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  30a8fd08-2242-4239-8d98-6f56c65592a4: # Craft Portfolio
    enabledByDefault: true
    hasUrls: true
    template: store-locator/index.twig
    uriFormat: visit-us
type: single
